### ISSUE TITLE
feature: serialize staging directory conceptual units 

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/uchicagoldr-toolsuite#34]
Need to be able to serialize a staging directory's conceptual family units to disk

**Comment by bnbalsamo** [comment]
I had originally closed this issue with #46 - but I'm not sure if the original issue is in reference to serializing structures or families. Issue reopened

**Comment by verbalhanglider** [comment]
I am closing this issue again because serializing families will be a different structure. This is under archiving a stage structure milestone, which while not in production the code is written and has been tested and passed test. Ready for production
