### ISSUE TITLE
organize package according to new frameworks

### ISSUE THREAD

**Issue by bnbalsamo** [uchicago-library/uchicagoldr-toolsuite#37]
Initial package reorganization has served well as a guide for relativizing and organizing all of the existing classes, but as the project expands to encompass several new components (the collection record creator, the acquisition/accession record creator, the entire conceptual framework) our current package organization is in need of a revisit.

This thread should generate a comprehensive layout for the current package architecture with this extensibility (and potential extensibility to a metapackage framework) in mind, as well as the best practices for package organization moving forward.

**Comment by bnbalsamo** [comment]
I propose, if we want to begin moving towards a multi-package setup with optional dependencies on other portions of the tool suite we begin to split our current code base along those lines. This should cause minimal import drama because all of our imports are relative if we keep ourselves honest about how much functionality is part of the "core".

A (highly incomplete) mockup of this might be...

```
uchicagoldrtoolsuite/
    file_level/
        lib/
            abc/
                [...]
            [...]
        impl/
            internal/
                [...]
            [...]
        app/
            internal/
                [...]
            [...]
    conceptual_level/
        lib/
            abc/
                [...]
            [...]
        impl/
            internal/
                [...]
            [...]
        app/
            internal/
                [...]
            [...]
    core/
        lib/
            abc/
                [...]
            [...]
        impl/
            internal/
                [...]
            [...]
        app/
            abc/
                [...]
            internal/
                [...]
            [...]
```

The major divisions are set in place between the file level, the conceptual level, and the core, and each has a lib directory where abstract base classes and base classes can be defined. impl directories will house implementations of the base classes from lib, with the internals directory meant to house partial implementations which can act as parent classes to multiple implementations.

I suggest the the majority of the application framework be stored in core (thus it housing the app/abc directory) while other applications have an app folder and an internal folder, for the same purposes as the impl directories.

I've chosen to not pluralize any of the names for sake of consistancy

**Comment by bnbalsamo** [comment]
While in the process of reorganizing I began to notice some problems with the previous planning. Chief amongst these were:
1. lib contained abstract and concrete classes, which made it confusing to tell which was which
2. some ABCs were subclasses of other ABCs in the same folder - the file system stopped being an accurate/useful representation of abstraction
3. Imports in applications that required tools out of impl and lib were looking pretty horrendous

I decided to remedy this by unabashedly duplicating the abc directory to represent _layers of abstraction_. So the first layer of abstraction might be lib.abc, the next lib.abc.abc, the third lib.abc.abc (currently we're only two deep). 

This seems a bit confusing at first (and admittedly it does take some extra brain cycles when dealing with project wide stuff like large scale tests), but it works surprisingly well using relative imports and keeping yourself honest when using classes. No module should ever (in standard use cases) need anything from .abc.abc.\* if we've designed our abstract base classes correctly. In the case of a first level of abstraction you only need to remember that .abc is where the abstract classes for this level of the model should be.

This also means we can do away with impl entirely, and say that _everything_ in lib is a concrete class (or a mixin, I've yet to really jump in with how we should handle these).

With this solution the repo now has three major subpackage divisions to allow for splitting the subpackages into freestanding packages in the future. "Core", "bit-level" (borrowing a term here to further distance naming from being file-centric), and "conceptual".

Each package has an app dir and a lib dir, app contains all the application tools, lib contains the library code those applications should use. There associated abstract base classes are in the appropriate abc dirs.

With this in place the repository is currently looking like the following:

```
uchicagoldrtoolsuite
├── bit_level
│   ├── app
│   │   ├── archiver.py
│   │   ├── premisobjectcreator.py
│   │   ├── premisrestrictionsetter.py
│   │   ├── pruner.py
│   │   ├── stager.py
│   │   └── technicalmetadatacreator.py
│   └── lib
│       ├── abc
│       │   ├── abc
│       │   │   ├── packager.py
│       │   │   ├── serializationreader.py
│       │   │   └── serializationwriter.py
│       │   ├── ldritem.py
│       │   ├── materialsuitepackager.py
│       │   ├── segmentpackager.py
│       │   ├── stageserializationreader.py
│       │   ├── stageserializationwriter.py
│       │   └── structure.py
│       ├── absolutefilepathtree.py
│       ├── archivestructure.py
│       ├── filepathtree.py
│       ├── filesystemarchivestructurewriter.py
│       ├── filesystemmaterialsuitepackager.py
│       ├── filesystemsegmentpackager.py
│       ├── filesystemstagereader.py
│       ├── filesystemstagewriter.py
│       ├── filewalker.py
│       ├── ldritemoperations.py
│       ├── ldrpath.py
│       ├── ldrurl.py
│       ├── materialsuite.py
│       ├── premisextensionnodes.py
│       ├── premisobjectrecordcreator.py
│       ├── rootedpath.py
│       ├── segment.py
│       ├── stage.py
│       └── technicalmetadatarecordcreator.py
├── conceptual
│   ├── app
│   └── lib
│       └── abc
└── core
    ├── app
    │   ├── abc
    │   │   ├── abc
    │   │   │   └── app.py
    │   │   └── cliapp.py
    │   ├── aru.py
    │   └── postinstall.py
    └── lib
        ├── abc
        ├── accessionrecorder.py
        ├── bash_cmd.py
        ├── confreader.py
        └── convenience.py

15 directories, 42 files
```

**Comment by verbalhanglider** [comment]
this looks useful. I had concerns with the nested abc packages, but I am reasonably assuaged that the enforced discipline of having it that way outweighs any concern that I have that this is evidence of over-engineering.
