### ISSUE TITLE
bug: ldrpath.read() to byte data and ldrpath.write(byte_data) creating bad copies

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/uchicagoldr-toolsuite#38]
It appears that the code in the write() method of this link 

https://github.com/uchicago-library/uchicagoldr-toolsuite/blob/structuring/uchicagoldrtoolsuite/lib/structuring/stagingdirectorywriter.py

generates file names that make sense but the files are un-openable.

**Comment by bnbalsamo** [comment]
Hmm - I'm not running into any problems:

```
>>> from uchicagoldrtoolsuite.lib.structuring.ldrpathregularfile import LDRPathRegularFile
>>> x = LDRPathRegularFile('test.txt')
>>> with x.open('w') as f:
...     f.write(b'test_data\n')
... 
<_io.BufferedWriter name='test.txt'>
True
>>> exit()
$ cat test.txt
test_data
$
```

I strongly suspect the syntax on line 46 may be the culprit. 
`today_str = b"%s" % today_str`
I did a bit of digging into the mechanics of how that works and couldn't for the life of me actually get that syntax to fire.

```
>>> from datetime import datetime
>>> today = datetime.today()
>>> today_str = "manifest generated on {}".\
... format(str(today.year) + '-' +
... str(today.month) + '-' +
... str(today.day))
>>> today_str
'manifest generated on 2016-4-27'
>>> today_str_bytes = b"%s" % today_str
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %b requires bytes, or an object that implements __bytes__, not 'str'
>>> today_str_decoded = today_str.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'decode'
>>> today_str_decoded = decode(today_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'decode' is not defined
>>> today_str_decoded = bytes(today_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: string argument without an encoding
>>> today_str_decoded = bytes(today_str, "utf-8")
>>> today_str_decoded
b'manifest generated on 2016-4-27'
>>> from uchicagoldrtoolsuite.lib.structuring.ldrpathregularfile import LDRPathRegularFile
>>> x = LDRPathRegularFile('test.txt')
>>> with x.open('w') as f:
...     f.write(today_str_decoded)
... 
<_io.BufferedWriter name='test.txt'>
True
>>> exit()
$ cat test.txt
manifest generated on 2016-4-27$ 
```

So, python3 apparently [does away with str.decode() and decode()](https://docs.python.org/3/library/stdtypes.html#str.decode), but you can cast a string to bytes provided you know the encoding, which should, in the case of text we are creating, always be utf-8.

**Edit**

Some deeper digging has pointed me towards [PEP 461](http://legacy.python.org/dev/peps/pep-0461/) .

**Comment by verbalhanglider** [comment]
Bug was resolved. Solution was to do the following:

with read_file.open('rb') as read_file
    with write_file.open('wb'):
        buffer = read_file.read(blocksize)
        if buffer:
             write_file.write(buffer)
       else:
             break
