### ISSUE TITLE
feature: create a pruner cli app using the latest design specification

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/uchicagoldr-toolsuite#39]
This CLI app should read a staging directory and take a list of patterns to match the contents of that staging directory against.

**Comment by bnbalsamo** [comment]
See #92 as well

**Comment by bnbalsamo** [comment]
Work ongoing in two branches:

[Branch 1](https://github.com/uchicago-library/uchicagoldr-toolsuite/tree/pruner_rework) which implements a pruner with the bare minimum requirements, which works within the current set of tools which are being used in production and [Branch 2](https://github.com/uchicago-library/uchicagoldr-toolsuite/tree/manifest_formalization) which implements a more formalized pre-PREMIS manifest, and hooks the pruner fairly heavily to it.

Whether branch #2 survives in its current state of is too drastically effected by #97 to be of any use remains to be seen - though its concepts remain sound.

**Comment by bnbalsamo** [comment]
This issue now relates heavily to #92 

I propose it can be closed after the staging_tearup branch is merged into dev.

**Comment by bnbalsamo** [comment]
closed by #103 merge into dev
