### ISSUE TITLE
BUG?: AbsoluteFilePathTree contains file inspection functionality

### ISSUE THREAD

**Issue by bnbalsamo** [uchicago-library/uchicagoldr-toolsuite#51]
AbsoluteFilePathTree contains file inspection functionality - should that be stripped out as we have previously discussed?

This would also finish (I think) the process of making python-magic an optional dependency.

**Comment by bnbalsamo** [comment]
paging @verbalhanglider - If you're not using this functionality anywhere I'll tear it out and see if anything breaks.

**Comment by verbalhanglider** [comment]
Yes, it should be stripped out.
