### ISSUE TITLE
discussion: arf renames resource files after object identifers in their corresponding premis records

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/uchicagoldr-toolsuite#59]
This is an ongoing discussion about how to start moving reliance towards premis records as means of accessing resources and having completely obfuscated resource filenames that can make retrieval more automated

**Comment by bnbalsamo** [comment]
We've opted for this option for a variety of reasons after meeting a meeting between the LDR Team and the sysadmins.

Doing this will allow us to leverage pairtrees at both the accession level and the file level, as well as regularized encapsulation schemes for the Archive structures.

Our analysis of pairtree [drawn from the specification critique paperwork]:

Our thinking includes:
PairTrees provide definite benefits, both organizationally and technically, to the LDR. These include:
- Organization of material for human retrieval
- Organization of material for machine retrieval
- Differentiation of organization and content
- Avoids the use of client produced data in identifiers
- Avoids edge cases in data hierarchies that make prevent multi-platform portability
- Allows piecemeal processing with “globbing” and other operations available on the Unix command-line
- Keeps terminal output readable

Closing this issue, as we've come to a decision
