### ISSUE TITLE
Creating a new prefix directory in staging directory when a prefix already exists throws error

### ISSUE THREAD

**Issue by bnbalsamo** [uchicago-library/uchicagoldr-toolsuite#6]
When attempt to create a new prefix directory in a staging directory which already contains a prefix directory the following occurs:

Traceback (most recent call last):
  File "staging.py", line 57, in <module>
    _exit(main())
  File "staging.py", line 45, in main
    s.ingest(resume_partially_completed_run = args.resume)
  File "/Users/balsamo/Envs/ldr_dev/lib/python3.5/site-packages/uchicagoldr/tree.py", line 494, in ingest
    self.add_to_a_staging_environment()
  File "/Users/balsamo/Envs/ldr_dev/lib/python3.5/site-packages/uchicagoldr/tree.py", line 409, in add_to_a_staging_environment
    last_data_dir_number = past_data_dirs[-1].split(self.prefix)[1]
IndexError: list index out of range

**Comment by bnbalsamo** [comment]
https://github.com/uchicago-library/uchicagoldr-primary/tree/issue6
- Fixes original issue
- Fixes a bug in isolating the next prefix number in instances where the path for the staging dir contains as any substring the prefix

Pull request made:
https://github.com/uchicago-library/uchicagoldr-primary/pull/7

**Comment by verbalhanglider** [comment]
Due to a conflict in branch update, issue6->dev pull request is in conflict. I have copied the change in code into the dev branch. For this reason: I propose closing this issue and cancelling the pull request and marking this issue as resolved,
